<a href="https://colab.research.google.com/github/pham156/pytorch-learning/blob/main/PyTorch_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Wed Sep 25 14:13:01 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


In [ ]:
scalar = torch.tensor(7)

In [ ]:
vector = torch.tensor([7,7])

In [ ]:
matrix = torch.tensor([[7,8],[9,10]])

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor
# random_tensor.dtype
# random_tensor.shape
# random_tensor.device

# zeros = torch.zeros(size=(3,4)) #[[0,0,...]]
# ones = torch.ones(size=(3,4)) #[[1,1,...]]
# range = torch.range(0,10) #[0,1,...]
# range = torch.arange(start=0, end=1000, step=10) #[0,10,20,...]

tensor([[0.3383, 0.5877, 0.7034, 0.0799],
        [0.3821, 0.1462, 0.8854, 0.7039],
        [0.5260, 0.1631, 0.3300, 0.3210]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))

In [ ]:
float_32_tensor = torch.tensor([3,6,9],dtype=None,device=None,requires_grad=False)

In [ ]:
# manipulating
tensor = torch.tensor([1,2,3])
tensor_2 = torch.tensor([2,3,4])
print(tensor + 10) # torch.add(tensor, 10)
print(tensor - 10)
print(tensor * 10) # torch.mul(tensor, 10)
print(tensor * tensor_2) # element wise
print(tensor @ tensor_2) # torch.matmul(tensor, tensor_2) # shape(a,b) @ shape(b,a)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([ 2,  6, 12])
tensor(20)


In [ ]:
# aggregation
tensor.min() # torch.min(tensor)
tensor.max() # torch.max(tensor)
tensor.type(torch.float32).mean() # torch.mean(tensor) # only for float32 type
tensor.argmin()
tensor.argmax()

tensor(2)

In [ ]:
x = torch.arange(1., 10.)

In [ ]:
x_reshaped = x.reshape(1,1,3,3) # reshape x # product of shape = # in x
z = x.view(3,3) # z: x view # change z also change x, because tensor share memory
x_stacked = torch.stack([x,x], dim=1) # dim <= dim(x)

In [ ]:
x_squeezed = x_reshaped.squeeze() # remove extra dim
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_permuted = x_reshaped.permute(3,2,0,1) #shift axis 0->2, 1->3, 2->1, 3->0

In [ ]:
x = torch.arange(1., 10.).reshape(1,3,3)
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [ ]:
x[0,0] # x[0][0]
x[:,0] # ":" select all of a target dimension
x[:,:,0] # only index 1 of 2nd dim

tensor([[1., 2., 3.]])

In [ ]:
# np -> tensor
array = np.arange(1., 8,)
tensor = torch.from_numpy(array).type(torch.float64)
numpy_tensor = tensor.numpy()

In [ ]:
torch.manual_seed(42) # make random not so random, need to be in a same block
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])
device = 'cpu'
# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [ ]:
# Exercises
torch.manual_seed(0)
random_tensor_1 = torch.rand(7,7)
random_tensor_2 = torch.rand(1,7)
random_tensor_2_trans = random_tensor_2.permute(1,0)
print(random_tensor_1 @ random_tensor_2_trans)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [ ]:
torch.cuda.manual_seed(1234)

In [ ]:

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [ ]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
max = torch.max(tensor_C)
min = torch.min(tensor_C)
arg_max = torch.argmax(tensor_C)
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3), tensor(0))

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
